· 486
DATA SEGMENT USE16
		BUF DB 'QWERTYUIOP123'
		COUNT EQU $ -BUF
		MAX DB 'MAX=',?,0DH,0AH,'$'
DATA ENDS
CODE SEGMENT USE16
ASSUME CS:CODE,DS:DATA
BEG: 	MOV AX,DATA
		MOV DS,AX
		MOV AL,0
		;无符号最小数0 →AL
		LEA BX,BUF
		;串首址偏移量→BX
		MOV CX,COUNT
		;串长度→CX
LAST: 	CMP [BX],AL;比较
		JC NEXT
		MOV AL,[BX];大数→AL
NEXT: 	INC BX
		LOOP LAST ;循环计数
		MOV MAX+4,AL
		;最大数→MAX+4 单元
		MOV AH,9
		MOV DX,OFFSET MAX
		INT 21H ;显示结果
		MOV AH,4CH
		INT 21H ;返回DOS
CODE ENDS
END BEG
