.586
CMPDISP MACRO NN
LOCAL LAST,NEXT
		MOV DL,0 ;DL清0
LAST: 	CMP BEN,NN ;比较
		JB NEXT ;BEN ＜ NN 转
		INC DL ;DL加1
		SUB BEN,NN ;BEN-NN→BEN
		JMP LAST
NEXT: 	ADD DL,30H ;转换为ASCII码
ENDM

DATA SEGMENT USE16
		BEN DW 1287H ;4743
		TAB DW 10000,1000,100,10,1
		COUNT EQU ($-TAB)/2
		BUF DB COUNT DUP(?),'$' ; 输出缓冲区
DATA ENDS

CODE SEGMENT USE16
ASSUME CS:CODE,DS:DATA
BEG: 	MOV AX,DATA
		MOV DS,AX
		MOV CX,COUNT
		MOV BX,OFFSET TAB
		MOV SI,OFFSET BUF ;输出缓冲区地址→SI
AGA: 	MOV AX,[BX]
		CMPDISP AX ;调用宏得到ASCII码
		MOV [SI],DL ;将ASCII码保存到输出缓冲区中
		ADD BX,2 ;BX+2→BX
		INC SI
		LOOP AGA
		MOV SI,OFFSET BUF ;输出缓冲区地址重新→SI
NOSP: 	CMP BYTE PTR [SI],30H ;判断字符是否为‘0’
		JNZ DISP ;不等,跳转到DISP显示
		INC SI
		JMP NOSP
DISP: 	MOV AH,9 ; 显示十进制数
		MOV DX,SI
		INT 21H
		MOV AH,4CH
		INT 21H
CODE ENDS
END BEG
