.586
DATA SEGMENT USE16
		STR1 DB 30,?,30 DUP(?) ;输入字符串缓冲区
		STR2 DB 'WELCOME'
		COUNT EQU $-STR2 ;统计串长度
		FLAG DB 'N' ;存放比较结果，初始为’N’
DATA ENDS
CODE SEGMENT USE16
ASSUME CS:CODE,DS:DATA,ES:DATA
BEG: 	MOV AX，DATA
		MOV DS，AX ;DS初始化
		MOV ES，AX ;ES初始化
		MOV CX，COUNT
		MOV AH，0AH ;从键盘输入字符串STR2
		MOV DX，OFFSET STR1
		INT 21H
		MOV CL，STR1+1
		MOV CH，0 ;输入字符串长度→CX
		CMP CX，COUNT ;比较STR1和STR2的长度是否相等
		JNZ EXIT ;字符串比较不相等，跳转
		MOV SI，OFFSET STR1+2 ;原串首址→SI
		MOV DI，OFFSET STR2 ;目标区首址→DI
		CLD ;D标志为0,增址型
LOAD:	REPE CMPSB ;两字符串比较
		JNZ EXIT ; 字符串比较不相等，跳转
		MOV FLAG，'Y' ;字符串相等，置FLAG为’Y’
EXIT: 	MOV AH，4CH
		INT 21H
CODE ENDS
END BEG
